---
# tasks file for follower
- name: pull dap container image
  docker_image:
    name: "{{dap_image_name}}"
    tag: "{{dap_version}}"
    source: pull
  when: inventory_hostname in groups['followers']

- name: start dap follower container
  docker_container:
    name: "{{dap_follower_name}}"
    image: "{{dap_image_name}}:{{dap_version}}"
    restart_policy: always
    security_opts:
      - "seccomp:unconfined"
    ports:
      - "5432:5432"
      - "443:443"
    volumes:
      - seed:/seed
  when: inventory_hostname in groups['followers']

- name: get role of DAP follower container
  command: docker exec {{dap_follower_name}} evoke role
  register: container_role
  when: inventory_hostname in groups ['followers']

- name: get seed file
  command: docker exec {{ dap_master_container_name }} evoke seed follower {{ dap_follower_name }} 
  register: seed
  when:
    - inventory_hostname in groups['masters']
    - hostvars[item]['container_role']['stdout'] == "blank"
  with_items:
    - "{{ groups['followers']}}"

- name: configure followers
  include_tasks: configure-follower.yml
  when: 
    - hostvars[item]['container_role']['stdout'] == "blank"
    - inventory_hostname in groups ['followers']
  with_items:
    - "{{ groups['followers']}}"
